add_version_check_in_setup_bash
tier4/caret pull request #13
Opened 2022-06-22 08:21 UTC by rokamu623

とりあえず最低限の仕様を実装しました。
- /etc/issueからマシンのubuntuバージョンを取得
- 20.04と正規表現マッチしなかったらエラー文を吐いてスクリプトを終了

エラー文（仮置きです）
```
exit : ubuntu version is invalid
install ubuntu version 20.04
```

2022-06-22 08:26 UTC, rokamu623 commented
@takam5f2 
何らかのファイルに正規表現マッチさせる文字列を格納すれば、ソースコードに埋め込んだ`20.04`のマジックナンバーは削除できるはずです。

シェルスクリプトだと簡単にyamlファイルから設定を読み出す機構が存在しないので、プレーンテキスト（.txt）にするべきでしょうか？或いは、意味のない適当な拡張子（中身はプレーンテキスト）で命名すればいいでしょうか？

`ubuntu_version.txt` or `ubuntu.version`
中身は共通で
```20.04```

2022-06-22 12:54 UTC, takam5f2 commented on setup_caret.sh
> +MACHINE_UBUNTU_VERSION=`cat /etc/issue`
`source /etc/lsb-release` して ${DISTRIB_RELEASE} という方法はどうでしょうか？ 
/etc/issue だと冗長な感じが気になっています。
```
cat /etc/issue
Ubuntu 20.04.4 LTS \n \l

```

2022-06-24 00:11 UTC, rokamu623 commented
@takam5f2 
まとめてバージョンを記述できるのであれば、`ansible/playbook.yml`にubuntuの情報を記述するのは良いと思います。
ただ、yaml内に記述した情報をシェルスクリプトから参照する簡単な方法が無いのがネックかもしれません。

2022-06-24 02:24 UTC, rokamu623 commented on setup_caret.sh
> +TOOL_UBUNTU_VERSION=`cat ./ansible/playbook.yml | grep ubuntu | sed -e 's/.*\([0-9][0-9].[0-9][0-9]\).*/\1/g'`
やや無理矢理感がありますが、playbook.ymlからバージョンを読み込む処理を実装してみました。

ただ、's/.*\([0-9][0-9].[0-9][0-9]\).*/\1/g'を、柔軟性を考えて's/.*\([0-9.]\+\).*/\1/g'にしたところ、20.04を抽出したい処理が4だけしか抽出できなくなってしまいました。

グループ化()と繰り返し構文+は同時に使用できないなどあるのでしょうか？現在調査中です。

2022-06-27 02:24 UTC, takam5f2 commented on ansible/playbook.yml
> +    - { role: ubuntu, version: 20.04 }
ansible 側で ubuntu という role がないということでエラーが出るはずです。
デフォルトの値を管理しているファイルはこういうところになります。  
https://github.com/tier4/caret/blob/main/ansible/roles/ros2/defaults/main.yml

2022-06-27 02:37 UTC, takam5f2 requested changes

2022-06-27 02:37 UTC, takam5f2 commented on setup_caret.sh
> +TOOL_UBUNTU_VERSION=`cat ./ansible/playbook.yml | grep ubuntu | sed -e 's/.*\([0-9][0-9].[0-9][0-9]\).*/\1/g'`
https://github.com/tier4/caret/blob/main/ansible/roles/ros2/defaults/main.yml を前提に下のyamlをgivenとするとどうでしょうか？
```
ubuntu-release: 20.04
```

`grep file_path |  sed -e "s/[^0-9]*\([0-9\.]\+\)/\1/g"` だとうまく行くと思います。 最初の .* が `20.0` を含む表現になっていることが原因です。

2022-06-29 01:00 UTC, rokamu623 commented on ansible/playbook.yml
> +    - { role: ubuntu, version: 20.04 }
ansible周りのファイルを設定しました。

2022-06-29 01:00 UTC, rokamu623 commented on setup_caret.sh
> +TOOL_UBUNTU_VERSION=`cat ./ansible/playbook.yml | grep ubuntu | sed -e 's/.*\([0-9][0-9].[0-9][0-9]\).*/\1/g'`
正規表現を修正し、XX.XXを検出するように修正しました。

上記のansibleの件と合わせて修正の確認をお願いします。

2022-06-30 07:22 UTC, takam5f2 requested changes

2022-06-30 07:22 UTC, takam5f2 commented on ansible/playbook.yml
> +    - { role: ubuntu, version: 20.04 }
Ansible の既存の role の default に追加をお願いできますか？ ubuntu という role があると勘違いしてしまうためです。といっても他の role でも不要な変数が出てくるので、そこは考えものなんですが。

2022-06-30 07:22 UTC, takam5f2 commented on setup_caret.sh
> +TOOL_UBUNTU_VERSION=`cat ./ansible/playbook.yml | grep ubuntu | sed -e 's/[^0-9.]*\([0-9.]*\).*/\1/g'`
`s/[^0-9.]*\([0-9.]*\).*/\1/g'` で `[^0-9.]` のピリオドってエスケープ  (`\.`) 不要ですか？

2022-06-30 23:56 UTC, rokamu623 commented on setup_caret.sh
> +TOOL_UBUNTU_VERSION=`cat ./ansible/playbook.yml | grep ubuntu | sed -e 's/[^0-9.]*\([0-9.]*\).*/\1/g'`
この.は、ワイルドカードとしての.ではなく、XX.XX.XXに対応するための.です。
そのため、エスケープは不要だと思います。

2022-07-01 00:15 UTC, rokamu623 commented on ansible/playbook.yml
> +    - { role: ubuntu, version: 20.04 }
修正を行いました。caretロールの中にubuntu_version変数を定義しています。

2022-07-03 16:19 UTC, takam5f2 commented on setup_caret.sh
> +TOOL_UBUNTU_VERSION=`cat ./ansible/playbook.yml | grep ubuntu | sed -e 's/[^0-9.]*\([0-9.]*\).*/\1/g'`
エスケープは"ワイルドカードではなく、ピリオド扱いにする" ことを明示的にするためなので、ピリオド扱うにするためには エスケープは必要になります。
https://qiita.com/katsukii/items/1c1550f064b4686c04d4

あと `cat ./ansible/playbook.yml` は不要で、 `grep -e 'ubuntu-version' ./ansible/playbook.yml` だけで同じことができると思います。

2022-07-06 06:40 UTC, rokamu623 commented on setup_caret.sh
> +TOOL_UBUNTU_VERSION=`grep -e ubuntu_version ./ansible/playbook.yml | sed -E 's/[^0-9\.]*([0-9\.]*).*/\1/g'`
@takam5f2  指摘点修正しました。
Okamuraの環境下で動作することも確認済みです。

2022-07-06 06:43 UTC, rokamu623 commented on setup_caret.sh
> +TOOL_UBUNTU_VERSION=`grep -e 'ubuntu_version' ./ansible/playbook.yml | sed -E 's/[^0-9\.]*([0-9\.]*).*/\1/g'`
@takam5f2 指摘点修正しました。
Okamuraの環境下で動作することも確認済みです。

2022-07-07 09:44 UTC, takam5f2 approved these changes

2022-07-07 09:52 UTC, takam5f2 approved these changes
LGTM!

2022-07-07 09:52 UTC, merged