refactor: install packages using pip according to the requirements.txt and package.xml
tier4/caret pull request #14
Opened 2022-06-23 06:28 UTC by bopeng-saitama

Install packages using pip according to the requirements.txt and package.xml.
Since python3-bt2 , build-essential and ros2 tracing related packages are not in the rosdep list, no modifications were made.
Signed-off-by: bopeng-saitama <peng.b.203@ms.saitama-u.ac.jp>

2022-06-28 16:00 UTC, takam5f2 requested changes

2022-07-03 16:12 UTC, takam5f2 commented
@bopeng-saitama  
Thank you for updating. It seems almost good.
However, I found that pandas's version was 0.25.3 after installing it via ansible. 

Do you know the reason why pandas, whose version is later than 1.4.0, is not installed?

2022-07-04 02:56 UTC, bopeng-saitama commented
>
@takam5f2 
The reason for this problem is the requirment path in visualizer folder is wrong. Sorry for that. I have fix this problem.
`pip3 list

bokeh                                2.4.3
pybind11                            2.9.2
pandas                              1.4.3
colorcet                             3.0.0
`

2022-07-05 02:56 UTC, takam5f2 approved these changes
LGTM!

2022-07-05 02:56 UTC, merged